export const UPDATE_RATES = 'UPDATE_RATES'
export const CHANGE_BASE_CURRENCY = 'CHANGE_BASE_CURRENCY'
export const SELECT_EXCHANGE_CURRENCY = 'SELECT_EXCHANGE_CURRENCY'
export const DELETE_EXCHANGE_CURRENCY = 'DELETE_EXCHANGE_CURRENCY'

export const START = '_START'
export const SUCCESS = '_SUCCESS'
export const FAIL = '_FAIL'
